name: turf
description: A turf.js-like geospatial analysis library working with GeoJSON, written in pure Dart.
version: 0.0.3
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://github.com/dartclub/turf_dart
repository: https://github.com/dartclub/turf_dart

dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  dartclub_lint: ^0.4.2
  test: ^1.19.3
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  analyzer: ^2.7.0
  benchmark: ^0.3.0
